### ISSUE TITLE
Alert users their subscription is ending

### ISSUE THREAD

**Issue by torch2424** [Kondeo/ccra-book#15] opened 2016-01-18 05:16 UTC
We need to alert users that their subscription is ending if it ends within the week

**Comment by julianpoy** [comment] 2016-01-18 05:18
This should happen every /login or if they don't re-login, it should happen once. Perhaps store in localStorage alert shown for subscription date?

**Comment by julianpoy** [comment] 2016-01-18 05:22
Duplicate of #4

**Comment by torch2424** [comment] 2016-01-18 05:25
closing #4

**Comment by torch2424** [comment] 2016-01-18 05:25
in retrospect, should of closed this haha

**Comment by torch2424** [comment] 2016-01-18 05:34
subscription expiry should be ignored for admins

**Comment by torch2424** [comment] 2016-01-19 06:56
@julianpoy Speaking of admins, is there a boolean being passed with an admin user?

**Comment by torch2424** [comment] 2016-01-19 06:57
doing this in subAlert

**Closed** 2016-01-23 06:12 UTC
Labels: enhancement, question
